apiVersion: example.com/v1
kind: WebApp
metadata:
  name: nginx-app
  namespace: default
spec:
  image: nginx:1.25
  replicas: 3
  port: 80
  env:
  - name: ENVIRONMENT
    value: production
  - name: LOG_LEVEL
    value: info
